"""Diagnostics for target block-verification consistency.

Speculative decoding verifies several draft tokens with one target forward pass.
On low-precision accelerators, that q_len>1 path can use different kernels from
one-token autoregressive decoding. These helpers measure whether the target's
block argmax sequence stays identical to its own q_len=1 greedy reference.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

import torch


@dataclass(slots=True, frozen=True)
class BlockMismatch:
    position: int
    reference_token_id: int
    predicted_token_id: int
    predicted_margin: float

    def to_dict(self) -> dict[str, int | float]:
        return asdict(self)


@dataclass(slots=True, frozen=True)
class BlockConsistencyReport:
    block_size: int
    tokens_checked: int
    mismatch_count: int
    exact_match: bool
    mismatches: tuple[BlockMismatch, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "block_size": self.block_size,
            "tokens_checked": self.tokens_checked,
            "mismatch_count": self.mismatch_count,
            "exact_match": self.exact_match,
            "mismatches": [row.to_dict() for row in self.mismatches],
        }


@torch.inference_mode()
def diagnose_target_block_consistency(
    model: Any,
    input_ids: torch.Tensor,
    reference_token_ids: torch.Tensor,
    *,
    block_size: int,
) -> BlockConsistencyReport:
    """Compare q_len>1 block predictions with a q_len=1 greedy reference.

    ``reference_token_ids`` should be generated by the same target model using
    incremental greedy decoding. The function feeds that known sequence back in
    blocks and records every position where the target's block-path argmax
    differs from the reference token.
    """

    if input_ids.ndim != 2 or input_ids.shape[0] != 1:
        raise ValueError("input_ids must have shape [1, prompt_length].")
    if reference_token_ids.ndim == 2:
        if reference_token_ids.shape[0] != 1:
            raise ValueError("reference_token_ids must have batch size one.")
        reference = reference_token_ids[0]
    elif reference_token_ids.ndim == 1:
        reference = reference_token_ids
    else:
        raise ValueError("reference_token_ids must be rank one or two.")
    if reference.numel() < 1:
        raise ValueError("reference_token_ids cannot be empty.")
    if block_size <= 0:
        raise ValueError("block_size must be positive.")

    prompt_outputs = model(input_ids=input_ids, use_cache=True)
    cache = prompt_outputs.past_key_values
    next_logits = prompt_outputs.logits[:, -1, :]

    mismatches: list[BlockMismatch] = []
    position = 0

    while position < int(reference.numel()):
        block = reference[position : position + block_size].unsqueeze(0)
        block_outputs = model(
            input_ids=block,
            past_key_values=cache,
            use_cache=True,
        )

        first_logits = next_logits.unsqueeze(1)
        if block.shape[1] > 1:
            verification_logits = torch.cat(
                [first_logits, block_outputs.logits[:, :-1, :]],
                dim=1,
            )
        else:
            verification_logits = first_logits

        predictions = torch.argmax(verification_logits, dim=-1)
        top_two = torch.topk(
            verification_logits.float(),
            k=min(2, verification_logits.shape[-1]),
            dim=-1,
        ).values
        if top_two.shape[-1] == 1:
            margins = torch.full_like(top_two[..., 0], float("inf"))
        else:
            margins = top_two[..., 0] - top_two[..., 1]

        difference = (predictions != block)[0]
        for local_position in torch.nonzero(
            difference,
            as_tuple=False,
        ).flatten():
            local_index = int(local_position.item())
            mismatches.append(
                BlockMismatch(
                    position=position + local_index,
                    reference_token_id=int(block[0, local_index].item()),
                    predicted_token_id=int(predictions[0, local_index].item()),
                    predicted_margin=float(margins[0, local_index].item()),
                )
            )

        cache = block_outputs.past_key_values
        next_logits = block_outputs.logits[:, -1, :]
        position += int(block.shape[1])

    return BlockConsistencyReport(
        block_size=block_size,
        tokens_checked=int(reference.numel()),
        mismatch_count=len(mismatches),
        exact_match=not mismatches,
        mismatches=tuple(mismatches),
    )
