"""Clean and audit the Stardew SFT candidate pool (PR1, Steps 3-7).

Reads the immutable raw candidate pool (``data/stardew/candidates.jsonl``)
and produces a normalized candidate pool with a controlled taxonomy, honest
review-state metadata, canonical source pages, deterministic knowledge
grouping, and an explicit rejected-record trail. This script never modifies
the raw input file.

If ``data/stardew/sft/review_log.jsonl`` exists, human review decisions in
it are applied on top of the automated pass and take precedence. Do not
hand-edit ``candidates.normalized.jsonl`` directly to record a review
decision -- it is regenerated by this script and any such edit is silently
lost on the next run. Add an entry to the review log instead.

This script does NOT decide train/validation/eval membership -- that is
``scripts/split_stardew_sft_data.py``'s job, which consumes this script's
normalized output.

Outputs:
    data/stardew/sft/candidates.normalized.jsonl  (all records, normalized)
    data/stardew/sft/rejected.jsonl               (rejected subset only)
    data/stardew/reports/sft_cleaning_report.json (taxonomy + dedup + leakage evidence)

Usage:
    python scripts/clean_stardew_sft_data.py \\
        --input data/stardew/candidates.jsonl \\
        --outdir data/stardew/sft \\
        --report data/stardew/reports/sft_cleaning_report.json
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.games.stardew.sft_sources import (  # noqa: E402
    build_canonical_title_index,
    canonicalize_record_sources,
)
from src.games.stardew.sft_taxonomy import TAXONOMY_VERSION, classify_category  # noqa: E402
from src.games.stardew.sft_text_utils import (  # noqa: E402
    extract_single_turn_qa,
    mask_template,
    normalize_text,
)

DATASET_VERSION = "2.0.0-candidate"
TEMPLATE_SIMILARITY_THRESHOLD = 0.85
NEAR_DUPLICATE_THRESHOLD = 0.90
MIN_TEMPLATE_LENGTH = 20


class UnionFind:
    def __init__(self, keys: list[str]) -> None:
        self._parent = {key: key for key in keys}

    def find(self, key: str) -> str:
        root = key
        while self._parent[root] != root:
            root = self._parent[root]
        while self._parent[key] != root:
            self._parent[key], key = root, self._parent[key]
        return root

    def union(self, a: str, b: str) -> None:
        root_a, root_b = self.find(a), self.find(b)
        if root_a == root_b:
            return
        # Deterministic tie-break so output does not depend on call order.
        if root_b < root_a:
            root_a, root_b = root_b, root_a
        self._parent[root_b] = root_a


@dataclass
class CleaningStats:
    unmapped_categories: Counter = field(default_factory=Counter)
    rejection_reason_counts: Counter = field(default_factory=Counter)
    task_family_counts: Counter = field(default_factory=Counter)
    intent_counts: Counter = field(default_factory=Counter)
    review_status_counts: Counter = field(default_factory=Counter)
    source_casing_merges: list[dict[str, Any]] = field(default_factory=list)
    template_leakage_pairs: list[dict[str, Any]] = field(default_factory=list)
    review_log_applied_count: int = 0
    review_log_unmatched_ids: list[str] = field(default_factory=list)
    review_log_overrides_of_automated_rejection: int = 0
    review_log_overrides_to_rejection: int = 0


def load_raw_records(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)
            except json.JSONDecodeError as error:
                raise SystemExit(
                    f"Invalid JSON at {path}:{line_number}: {error}"
                )
            if not isinstance(data, dict):
                raise SystemExit(f"{path}:{line_number} is not a JSON object")
            records.append(data)
    return records


def has_auditable_review_evidence(raw: dict[str, Any]) -> bool:
    """Whether a record carries evidence a human actually reviewed it.

    A boolean ``verified: true`` flag alone is not evidence -- it is exactly
    the claim this pipeline exists to stop trusting blindly. Evidence means
    a timestamp and/or notes tying the claim to an actual review event.
    """

    reviewed_at = raw.get("reviewed_at")
    review_notes = raw.get("review_notes")
    reviewer = raw.get("reviewer")

    return bool(
        (isinstance(reviewed_at, str) and reviewed_at.strip())
        or (isinstance(review_notes, str) and review_notes.strip())
        or (isinstance(reviewer, str) and reviewer.strip())
    )


def normalize_records(
    raw_records: list[dict[str, Any]],
    stats: CleaningStats,
) -> list[dict[str, Any]]:
    all_urls = [
        url
        for raw in raw_records
        for url in raw.get("source_urls", [])
        if isinstance(url, str)
    ]
    canonical_index = build_canonical_title_index(all_urls)

    normalized: list[dict[str, Any]] = []

    for index, raw in enumerate(raw_records, start=1):
        new_id = f"sdv_sft_{index:06d}"
        legacy_id = raw.get("id")
        original_category = raw.get("category")

        classification = classify_category(original_category)
        if not classification.matched:
            stats.unmapped_categories[str(original_category)] += 1

        stats.task_family_counts[classification.task_family] += 1
        stats.intent_counts[classification.intent] += 1

        raw_urls = raw.get("source_urls") if isinstance(raw.get("source_urls"), list) else []
        source_pages, group_keys, source_issues = canonicalize_record_sources(
            raw_urls, canonical_index
        )

        evidenced = has_auditable_review_evidence(raw)

        record = {
            "id": new_id,
            "legacy_id": legacy_id,
            "game": "stardew_valley",
            "domain": "stardew_valley",
            "language": raw.get("language"),
            "messages": raw.get("messages"),
            "intent": classification.intent,
            "task_family": classification.task_family,
            "topic": classification.topic,
            "category": original_category,
            "original_category": original_category,
            "knowledge_group": None,  # assigned in a later pass
            "required_facts": raw.get("required_facts"),
            "forbidden_errors": raw.get("forbidden_errors"),
            "source_urls": raw_urls,
            "source_pages": source_pages,
            "source_group_keys": group_keys,
            "generation_method": raw.get("generation_method"),
            "verified": evidenced,
            "review_status": "approved" if evidenced else "pending",
            "rejection_reasons": [],
            "legacy_reviewed_by": raw.get("reviewed_by"),
            "annotator": None,
            "reviewer": raw.get("reviewer") if evidenced else None,
            "reviewed_at": raw.get("reviewed_at") if evidenced else None,
            "review_notes": raw.get("review_notes") if evidenced else None,
            "dataset_version": DATASET_VERSION,
            "legacy_dataset_version": raw.get("dataset_version"),
            "taxonomy_version": TAXONOMY_VERSION,
            "split": "unassigned",
            "_source_issues": source_issues,
        }

        normalized.append(record)

    return normalized


def apply_structural_and_duplicate_checks(
    records: list[dict[str, Any]],
    stats: CleaningStats,
) -> None:
    seen_questions: dict[str, str] = {}
    seen_answers: dict[str, str] = {}

    for record in records:
        reasons: list[str] = []

        qa = extract_single_turn_qa(record["messages"])
        if qa is None:
            reasons.append("malformed_messages")
        else:
            question, answer = qa

            if not record["source_urls"]:
                reasons.append("missing_source")
            elif not record["source_pages"]:
                reasons.append("unsupported_source")

            if not isinstance(record.get("language"), str) or not record["language"].strip():
                reasons.append("invalid_metadata")
            if not isinstance(record.get("required_facts"), list):
                reasons.append("invalid_metadata")
            if not isinstance(record.get("forbidden_errors"), list):
                reasons.append("invalid_metadata")

            nq = normalize_text(question)
            na = normalize_text(answer)

            if nq in seen_questions:
                reasons.append("duplicate_question")
            elif na in seen_answers:
                reasons.append("duplicate_answer")

            # Register regardless of other reasons so a later genuine
            # duplicate is still caught relative to this first occurrence.
            seen_questions.setdefault(nq, record["id"])
            seen_answers.setdefault(na, record["id"])

        if reasons:
            record["review_status"] = "rejected"
            record["verified"] = False
            record["rejection_reasons"] = reasons
            for reason in reasons:
                stats.rejection_reason_counts[reason] += 1

        stats.review_status_counts[record["review_status"]] += 1


VALID_REVIEW_DECISIONS = {"approved", "rejected", "needs_changes"}


def load_review_log(path: Path) -> dict[str, dict[str, Any]]:
    """Load a human review-decision log, keyed by ``legacy_id``.

    The log is a separate, durable, git-tracked file
    (``data/stardew/sft/review_log.jsonl``) rather than something baked into
    the generated ``candidates.normalized.jsonl`` output, so review decisions
    survive re-running this script against an updated raw candidate pool.
    Each line requires ``legacy_id``, ``decision`` (one of
    ``VALID_REVIEW_DECISIONS``), ``reviewer``, and ``reviewed_at`` -- a
    decision without reviewer/timestamp attribution is not auditable and is
    rejected at load time rather than silently accepted.
    """

    entries: dict[str, dict[str, Any]] = {}

    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            line = raw_line.strip()
            if not line:
                continue
            entry = json.loads(line)

            legacy_id = entry.get("legacy_id")
            decision = entry.get("decision")
            reviewer = entry.get("reviewer")
            reviewed_at = entry.get("reviewed_at")

            if not isinstance(legacy_id, str) or not legacy_id.strip():
                raise SystemExit(f"{path}:{line_number}: missing 'legacy_id'")
            if decision not in VALID_REVIEW_DECISIONS:
                raise SystemExit(
                    f"{path}:{line_number}: 'decision' must be one of "
                    f"{sorted(VALID_REVIEW_DECISIONS)}, got {decision!r}"
                )
            if not isinstance(reviewer, str) or not reviewer.strip():
                raise SystemExit(
                    f"{path}:{line_number}: 'reviewer' is required and must be non-empty "
                    "-- a review decision without attribution is not auditable"
                )
            if not isinstance(reviewed_at, str) or not reviewed_at.strip():
                raise SystemExit(
                    f"{path}:{line_number}: 'reviewed_at' is required and must be non-empty"
                )

            entries[legacy_id] = entry

    return entries


def apply_review_log(
    records: list[dict[str, Any]],
    review_log: dict[str, dict[str, Any]],
    stats: CleaningStats,
) -> None:
    """Apply human review decisions on top of the automated pass.

    A human decision always wins over the automated structural/duplicate
    checks -- that is the entire point of having a review step. Approving a
    record the automated pass rejected (a false positive) or rejecting one
    it passed (a duplicate the exact-text matcher missed) are both valid
    overrides and are counted separately so the audit trail shows where a
    human disagreed with the automation.
    """

    matched_legacy_ids: set[str] = set()

    for record in records:
        entry = review_log.get(record["legacy_id"])
        if entry is None:
            continue

        matched_legacy_ids.add(record["legacy_id"])
        stats.review_log_applied_count += 1

        was_auto_rejected = record["review_status"] == "rejected"
        decision = entry["decision"]

        if was_auto_rejected and decision != "rejected":
            stats.review_log_overrides_of_automated_rejection += 1
        if not was_auto_rejected and decision == "rejected":
            stats.review_log_overrides_to_rejection += 1

        record["reviewer"] = entry["reviewer"]
        record["reviewed_at"] = entry["reviewed_at"]
        record["review_notes"] = entry.get("review_notes")

        if decision == "approved":
            record["review_status"] = "approved"
            record["verified"] = True
            record["rejection_reasons"] = []
        elif decision == "rejected":
            record["review_status"] = "rejected"
            record["verified"] = False
            record["rejection_reasons"] = (
                entry.get("rejection_reasons") or record["rejection_reasons"] or ["factual_review_required"]
            )
        else:  # needs_changes
            record["review_status"] = "needs_changes"
            record["verified"] = False
            record["rejection_reasons"] = []

    stats.review_log_unmatched_ids = sorted(
        set(review_log.keys()) - matched_legacy_ids
    )

    # Recompute review_status_counts / rejection_reason_counts from scratch
    # now that the log has been applied, rather than incrementally patching
    # the automated-pass counts.
    stats.review_status_counts = Counter(r["review_status"] for r in records)
    stats.rejection_reason_counts = Counter(
        reason
        for r in records
        for reason in r["rejection_reasons"]
    )


def assign_knowledge_groups(
    records: list[dict[str, Any]],
    stats: CleaningStats,
) -> None:
    uf = UnionFind([r["id"] for r in records])

    # Union every record with the others that cite an overlapping canonical
    # source page.
    by_page: dict[str, list[str]] = defaultdict(list)
    for record in records:
        for key in record["source_group_keys"]:
            by_page[key].append(record["id"])

    for ids_sharing_page in by_page.values():
        for other_id in ids_sharing_page[1:]:
            uf.union(ids_sharing_page[0], other_id)

    # Two distinct fuzzy-similarity passes, deliberately different in scope:
    #
    # 1. Near-duplicate auto-union (this drives the actual split grouping):
    #    compares the *unmasked* normalized question. Threshold is high
    #    (NEAR_DUPLICATE_THRESHOLD) so it only merges genuine paraphrase
    #    duplicates of the same real record (e.g. the same question copied
    #    with one word changed), not "any two questions that happen to share
    #    a generic sentence shape". Entity-masking two different real items
    #    (e.g. "How can a player obtain Smallmouth Bass" vs "...Taro Root")
    #    down to the same template and auto-merging their groups was tried
    #    and rejected: it collapsed most of item_acquisition into one giant
    #    knowledge group and produced a validation split bigger than train.
    #
    # 2. Template-leakage reporting (informational only, does not union):
    #    compares *entity-masked* templates so a human reviewer can see
    #    every place the pool over-relies on one generic question shape,
    #    per Step 6's "flag for human review rather than deleting blindly".
    entries: list[tuple[str, str, dict[str, Any]]] = []
    for record in records:
        qa = extract_single_turn_qa(record["messages"])
        if qa is None:
            continue
        question, _answer = qa
        entity_phrases = [page.replace("_", " ") for page in record["source_pages"]]
        entries.append(
            (normalize_text(question), mask_template(question, entity_phrases), record)
        )

    near_dup_buckets: dict[str, list[tuple[str, str, dict[str, Any]]]] = defaultdict(list)
    for unmasked, masked, record in entries:
        prefix_key = " ".join(unmasked.split()[:3])
        near_dup_buckets[prefix_key].append((unmasked, masked, record))

    for bucket in near_dup_buckets.values():
        for i in range(len(bucket)):
            left_unmasked, left_masked, left_record = bucket[i]
            if len(left_unmasked) < MIN_TEMPLATE_LENGTH:
                continue
            for j in range(i + 1, len(bucket)):
                right_unmasked, right_masked, right_record = bucket[j]
                if len(right_unmasked) < MIN_TEMPLATE_LENGTH:
                    continue
                if set(left_record["source_group_keys"]) & set(right_record["source_group_keys"]):
                    continue

                near_dup_ratio = SequenceMatcher(None, left_unmasked, right_unmasked).ratio()
                if (
                    near_dup_ratio >= NEAR_DUPLICATE_THRESHOLD
                    and uf.find(left_record["id"]) != uf.find(right_record["id"])
                ):
                    uf.union(left_record["id"], right_record["id"])

                template_ratio = SequenceMatcher(None, left_masked, right_masked).ratio()
                if template_ratio >= TEMPLATE_SIMILARITY_THRESHOLD:
                    stats.template_leakage_pairs.append(
                        {
                            "left_id": left_record["id"],
                            "left_legacy_id": left_record["legacy_id"],
                            "right_id": right_record["id"],
                            "right_legacy_id": right_record["legacy_id"],
                            "left_task_family": left_record["task_family"],
                            "right_task_family": right_record["task_family"],
                            "template_similarity": round(template_ratio, 4),
                            "unmasked_similarity": round(near_dup_ratio, 4),
                            "auto_grouped": near_dup_ratio >= NEAR_DUPLICATE_THRESHOLD,
                            "left_source_pages": left_record["source_pages"],
                            "right_source_pages": right_record["source_pages"],
                        }
                    )

    # Assign deterministic, human-readable group ids: order connected
    # components by the smallest record id they contain.
    components: dict[str, list[str]] = defaultdict(list)
    for record in records:
        components[uf.find(record["id"])].append(record["id"])

    ordered_roots = sorted(components.keys(), key=lambda root: min(components[root]))
    group_id_by_root = {
        root: f"kg_{position:06d}" for position, root in enumerate(ordered_roots, start=1)
    }

    for record in records:
        record["knowledge_group"] = group_id_by_root[uf.find(record["id"])]


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            public_record = {k: v for k, v in record.items() if not k.startswith("_")}
            handle.write(json.dumps(public_record, ensure_ascii=False) + "\n")


def write_report(path: Path, stats: CleaningStats, total: int, kept: int, rejected: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "taxonomy_version": TAXONOMY_VERSION,
        "dataset_version": DATASET_VERSION,
        "template_similarity_threshold": TEMPLATE_SIMILARITY_THRESHOLD,
        "totals": {"total": total, "kept": kept, "rejected": rejected},
        "review_status_counts": dict(stats.review_status_counts),
        "rejection_reason_counts": dict(stats.rejection_reason_counts),
        "task_family_counts": dict(stats.task_family_counts),
        "intent_counts": dict(stats.intent_counts),
        "unmapped_category_counts": dict(stats.unmapped_categories),
        "unmapped_category_total": sum(stats.unmapped_categories.values()),
        "template_leakage_pair_count": len(stats.template_leakage_pairs),
        # Capped for file size; the count above is always the true total.
        "template_leakage_pairs_sample": stats.template_leakage_pairs[:500],
        "review_log_applied_count": stats.review_log_applied_count,
        "review_log_unmatched_ids": stats.review_log_unmatched_ids,
        "review_log_overrides_of_automated_rejection": stats.review_log_overrides_of_automated_rejection,
        "review_log_overrides_to_rejection": stats.review_log_overrides_to_rejection,
    }
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False, sort_keys=True)
        handle.write("\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=Path("data/stardew/candidates.jsonl"))
    parser.add_argument("--outdir", type=Path, default=Path("data/stardew/sft"))
    parser.add_argument(
        "--report", type=Path, default=Path("data/stardew/reports/sft_cleaning_report.json")
    )
    parser.add_argument(
        "--review-log",
        type=Path,
        default=Path("data/stardew/sft/review_log.jsonl"),
        help=(
            "Optional human review-decision log (legacy_id -> approved/rejected/"
            "needs_changes with reviewer attribution). Applied on top of the "
            "automated pass; overrides its decisions. Skipped if the file "
            "does not exist."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    stats = CleaningStats()

    raw_records = load_raw_records(args.input)
    normalized = normalize_records(raw_records, stats)
    apply_structural_and_duplicate_checks(normalized, stats)

    if args.review_log.exists():
        review_log = load_review_log(args.review_log)
        apply_review_log(normalized, review_log, stats)
    else:
        review_log = {}

    assign_knowledge_groups(normalized, stats)

    kept = [r for r in normalized if r["review_status"] != "rejected"]
    rejected = [r for r in normalized if r["review_status"] == "rejected"]

    write_jsonl(args.outdir / "candidates.normalized.jsonl", normalized)
    write_jsonl(args.outdir / "rejected.jsonl", rejected)
    write_report(args.report, stats, len(normalized), len(kept), len(rejected))

    print(f"Total input records: {len(raw_records)}")
    print(f"Normalized records written: {len(normalized)}")
    print(f"Kept (non-rejected): {len(kept)}")
    print(f"Rejected: {len(rejected)}  ({dict(stats.rejection_reason_counts)})")
    print(f"Unmapped categories: {sum(stats.unmapped_categories.values())} records "
          f"across {len(stats.unmapped_categories)} distinct categories")
    print(f"Template leakage pairs flagged: {len(stats.template_leakage_pairs)}")
    print(f"Knowledge groups: {len({r['knowledge_group'] for r in normalized})}")
    if review_log:
        print(
            f"Review log applied: {stats.review_log_applied_count}/{len(review_log)} entries matched "
            f"({len(stats.review_log_unmatched_ids)} unmatched); "
            f"{stats.review_log_overrides_of_automated_rejection} human overrides of automated "
            f"rejection, {stats.review_log_overrides_to_rejection} human overrides to rejection"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
