"""Prompt construction utilities for controlled benchmark workloads."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import torch


_PROMPT_CORPORA: dict[str, str] = {
    "technical": (
        "Explain how autoregressive transformer inference separates prompt prefill "
        "from token-by-token decoding. Discuss key-value caching, memory bandwidth, "
        "batching, latency, throughput, and the trade-offs that appear when sequence "
        "length grows. Use precise terminology and concrete engineering reasoning."
    ),
    "qa": (
        "Question: What factors determine the latency of a language model response? "
        "Answer carefully by distinguishing time to first token from time per output "
        "token, and describe how hardware, model size, prompt length, and batching "
        "affect the result."
    ),
    "summarization": (
        "Summarize the following engineering note while preserving every important "
        "constraint. A production inference service receives requests with different "
        "prompt and output lengths. Prefill work is compute intensive, decode work is "
        "memory bandwidth intensive, and queueing policy changes tail latency. The "
        "summary should identify assumptions, measurements, and conclusions."
    ),
    "coding": (
        "Write robust Python code for a benchmark harness that validates arguments, "
        "warms up the model, synchronizes accelerators, records prefill and decode "
        "timings, serializes results as JSON, and reports actionable error messages. "
        "Include type hints and avoid hidden global state."
    ),
}


@dataclass(frozen=True)
class PromptBatch:
    """An exact-length token batch plus a human-readable decoded prompt."""

    text: str
    input_ids: torch.Tensor
    attention_mask: torch.Tensor
    prompt_type: str
    target_tokens: int
    actual_tokens: int
    batch_size: int


def supported_prompt_types() -> tuple[str, ...]:
    """Return the supported synthetic benchmark prompt categories."""

    return tuple(sorted(_PROMPT_CORPORA))


def _validate_inputs(target_tokens: int, prompt_type: str, batch_size: int = 1) -> str:
    if isinstance(target_tokens, bool) or not isinstance(target_tokens, int):
        raise TypeError("target_tokens must be an integer.")
    if target_tokens < 1:
        raise ValueError("target_tokens must be at least 1.")
    if isinstance(batch_size, bool) or not isinstance(batch_size, int):
        raise TypeError("batch_size must be an integer.")
    if batch_size < 1:
        raise ValueError("batch_size must be at least 1.")

    normalized_type = str(prompt_type).strip().casefold()
    if normalized_type not in _PROMPT_CORPORA:
        raise ValueError(
            "Unsupported prompt_type. Expected one of: "
            + ", ".join(supported_prompt_types())
        )
    return normalized_type


def make_prompt(
    target_tokens: int,
    prompt_type: str = "technical",
    *,
    tokenizer: Any | None = None,
) -> str:
    """Build a deterministic prompt of approximately ``target_tokens`` tokens.

    Without a tokenizer, a whitespace-delimited word is used as the token proxy. When
    a tokenizer is supplied, the returned text is decoded from an exact-length token
    sequence generated by :func:`build_prompt_batch`.
    """

    normalized_type = _validate_inputs(target_tokens, prompt_type)
    if tokenizer is not None:
        return build_prompt_batch(
            tokenizer,
            target_tokens,
            prompt_type=normalized_type,
        ).text

    words = _PROMPT_CORPORA[normalized_type].split()
    repeated = [words[index % len(words)] for index in range(target_tokens)]
    return " ".join(repeated)


def _extract_token_ids(encoded: Any) -> list[int]:
    if isinstance(encoded, dict):
        encoded = encoded.get("input_ids")
    elif hasattr(encoded, "input_ids"):
        encoded = encoded.input_ids

    if isinstance(encoded, torch.Tensor):
        values = encoded.detach().cpu()
        if values.ndim == 2:
            values = values[0]
        return [int(value) for value in values.tolist()]

    if isinstance(encoded, (list, tuple)):
        if encoded and isinstance(encoded[0], (list, tuple)):
            encoded = encoded[0]
        return [int(value) for value in encoded]

    raise TypeError("Tokenizer output does not contain a supported input_ids value.")


def build_prompt_batch(
    tokenizer: Any,
    target_tokens: int,
    *,
    prompt_type: str = "technical",
    batch_size: int = 1,
    device: str | torch.device | None = None,
) -> PromptBatch:
    """Create an exact-length input tensor for reproducible benchmark cases.

    The seed corpus is tokenized without model-added special tokens, then repeated and
    cropped to the requested length. This avoids the common benchmark error where a
    nominal character or word count is mistaken for the model's actual token count.
    """

    normalized_type = _validate_inputs(target_tokens, prompt_type, batch_size)
    if tokenizer is None:
        raise TypeError("tokenizer cannot be None.")

    corpus = _PROMPT_CORPORA[normalized_type]
    try:
        encoded = tokenizer(
            corpus,
            add_special_tokens=False,
            return_attention_mask=False,
        )
    except TypeError:
        encoded = tokenizer(corpus)

    seed_ids = _extract_token_ids(encoded)
    if not seed_ids:
        fallback_id = getattr(tokenizer, "bos_token_id", None)
        if fallback_id is None:
            fallback_id = getattr(tokenizer, "eos_token_id", None)
        if fallback_id is None:
            raise ValueError("Tokenizer produced no tokens and has no BOS/EOS fallback.")
        seed_ids = [int(fallback_id)]

    repeats = (target_tokens + len(seed_ids) - 1) // len(seed_ids)
    token_ids = (seed_ids * repeats)[:target_tokens]

    resolved_device = torch.device(device) if device is not None else torch.device("cpu")
    input_ids = torch.tensor(token_ids, dtype=torch.long, device=resolved_device)
    input_ids = input_ids.unsqueeze(0).repeat(batch_size, 1)
    attention_mask = torch.ones_like(input_ids)

    try:
        text = tokenizer.decode(token_ids, skip_special_tokens=False)
    except TypeError:
        text = tokenizer.decode(token_ids)
    except AttributeError:
        text = corpus

    return PromptBatch(
        text=str(text),
        input_ids=input_ids,
        attention_mask=attention_mask,
        prompt_type=normalized_type,
        target_tokens=target_tokens,
        actual_tokens=int(input_ids.shape[1]),
        batch_size=batch_size,
    )
